#.travis.yml
language: java

dist: trusty

jdk:
  - oraclejdk8

arch:
  - amd64
  - arm64

cache:
  directories:
    - $HOME/.m2

install:
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
     sudo apt-get update;
     sudo apt-get install -y maven openjdk-8-jdk;
     export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-arm64;
     export PATH=$JAVA_HOME/bin:$PATH;
    fi
  - ./mvnw clean install -Pci-install -B -U -e
  - sh ./tools/check_format.sh

script:
  - travis_retry ./mvnw package -Pci-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
